# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.31

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /Users/joepuplava/Downloads/cmake-3.31.8-macos-universal/CMake.app/Contents/bin/cmake

# The command to remove a file.
RM = /Users/joepuplava/Downloads/cmake-3.31.8-macos-universal/CMake.app/Contents/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/joepuplava/Documents/Bater_Research/DPOpt

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/joepuplava/Documents/Bater_Research/DPOpt

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running tests..."
	/Users/joepuplava/Downloads/cmake-3.31.8-macos-universal/CMake.app/Contents/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/Users/joepuplava/Downloads/cmake-3.31.8-macos-universal/CMake.app/Contents/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/Users/joepuplava/Downloads/cmake-3.31.8-macos-universal/CMake.app/Contents/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/Users/joepuplava/Downloads/cmake-3.31.8-macos-universal/CMake.app/Contents/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/Users/joepuplava/Downloads/cmake-3.31.8-macos-universal/CMake.app/Contents/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/Users/joepuplava/Downloads/cmake-3.31.8-macos-universal/CMake.app/Contents/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/Users/joepuplava/Downloads/cmake-3.31.8-macos-universal/CMake.app/Contents/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/Users/joepuplava/Downloads/cmake-3.31.8-macos-universal/CMake.app/Contents/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/Users/joepuplava/Downloads/cmake-3.31.8-macos-universal/CMake.app/Contents/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/joepuplava/Documents/Bater_Research/DPOpt/CMakeFiles /Users/joepuplava/Documents/Bater_Research/DPOpt//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/joepuplava/Documents/Bater_Research/DPOpt/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named test_joetest

# Build rule for target.
test_joetest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_joetest
.PHONY : test_joetest

# fast build rule for target.
test_joetest/fast:
	$(MAKE) $(MAKESILENT) -f test/CMakeFiles/test_joetest.dir/build.make test/CMakeFiles/test_joetest.dir/build
.PHONY : test_joetest/fast

#=============================================================================
# Target rules for targets named test_joetest2

# Build rule for target.
test_joetest2: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_joetest2
.PHONY : test_joetest2

# fast build rule for target.
test_joetest2/fast:
	$(MAKE) $(MAKESILENT) -f test/CMakeFiles/test_joetest2.dir/build.make test/CMakeFiles/test_joetest2.dir/build
.PHONY : test_joetest2/fast

#=============================================================================
# Target rules for targets named test_template1

# Build rule for target.
test_template1: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_template1
.PHONY : test_template1

# fast build rule for target.
test_template1/fast:
	$(MAKE) $(MAKESILENT) -f test/CMakeFiles/test_template1.dir/build.make test/CMakeFiles/test_template1.dir/build
.PHONY : test_template1/fast

#=============================================================================
# Target rules for targets named test_template2

# Build rule for target.
test_template2: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_template2
.PHONY : test_template2

# fast build rule for target.
test_template2/fast:
	$(MAKE) $(MAKESILENT) -f test/CMakeFiles/test_template2.dir/build.make test/CMakeFiles/test_template2.dir/build
.PHONY : test_template2/fast

#=============================================================================
# Target rules for targets named test_template3

# Build rule for target.
test_template3: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_template3
.PHONY : test_template3

# fast build rule for target.
test_template3/fast:
	$(MAKE) $(MAKESILENT) -f test/CMakeFiles/test_template3.dir/build.make test/CMakeFiles/test_template3.dir/build
.PHONY : test_template3/fast

#=============================================================================
# Target rules for targets named test_template4

# Build rule for target.
test_template4: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_template4
.PHONY : test_template4

# fast build rule for target.
test_template4/fast:
	$(MAKE) $(MAKESILENT) -f test/CMakeFiles/test_template4.dir/build.make test/CMakeFiles/test_template4.dir/build
.PHONY : test_template4/fast

#=============================================================================
# Target rules for targets named test_template1Test

# Build rule for target.
test_template1Test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_template1Test
.PHONY : test_template1Test

# fast build rule for target.
test_template1Test/fast:
	$(MAKE) $(MAKESILENT) -f test/CMakeFiles/test_template1Test.dir/build.make test/CMakeFiles/test_template1Test.dir/build
.PHONY : test_template1Test/fast

#=============================================================================
# Target rules for targets named test_template2Test

# Build rule for target.
test_template2Test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_template2Test
.PHONY : test_template2Test

# fast build rule for target.
test_template2Test/fast:
	$(MAKE) $(MAKESILENT) -f test/CMakeFiles/test_template2Test.dir/build.make test/CMakeFiles/test_template2Test.dir/build
.PHONY : test_template2Test/fast

#=============================================================================
# Target rules for targets named test_template3Test

# Build rule for target.
test_template3Test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_template3Test
.PHONY : test_template3Test

# fast build rule for target.
test_template3Test/fast:
	$(MAKE) $(MAKESILENT) -f test/CMakeFiles/test_template3Test.dir/build.make test/CMakeFiles/test_template3Test.dir/build
.PHONY : test_template3Test/fast

#=============================================================================
# Target rules for targets named test_template4Test

# Build rule for target.
test_template4Test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_template4Test
.PHONY : test_template4Test

# fast build rule for target.
test_template4Test/fast:
	$(MAKE) $(MAKESILENT) -f test/CMakeFiles/test_template4Test.dir/build.make test/CMakeFiles/test_template4Test.dir/build
.PHONY : test_template4Test/fast

#=============================================================================
# Target rules for targets named exp_q1

# Build rule for target.
exp_q1: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 exp_q1
.PHONY : exp_q1

# fast build rule for target.
exp_q1/fast:
	$(MAKE) $(MAKESILENT) -f exp/CMakeFiles/exp_q1.dir/build.make exp/CMakeFiles/exp_q1.dir/build
.PHONY : exp_q1/fast

#=============================================================================
# Target rules for targets named exp_q1_a

# Build rule for target.
exp_q1_a: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 exp_q1_a
.PHONY : exp_q1_a

# fast build rule for target.
exp_q1_a/fast:
	$(MAKE) $(MAKESILENT) -f exp/CMakeFiles/exp_q1_a.dir/build.make exp/CMakeFiles/exp_q1_a.dir/build
.PHONY : exp_q1_a/fast

#=============================================================================
# Target rules for targets named exp_q1_b

# Build rule for target.
exp_q1_b: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 exp_q1_b
.PHONY : exp_q1_b

# fast build rule for target.
exp_q1_b/fast:
	$(MAKE) $(MAKESILENT) -f exp/CMakeFiles/exp_q1_b.dir/build.make exp/CMakeFiles/exp_q1_b.dir/build
.PHONY : exp_q1_b/fast

#=============================================================================
# Target rules for targets named exp_q2

# Build rule for target.
exp_q2: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 exp_q2
.PHONY : exp_q2

# fast build rule for target.
exp_q2/fast:
	$(MAKE) $(MAKESILENT) -f exp/CMakeFiles/exp_q2.dir/build.make exp/CMakeFiles/exp_q2.dir/build
.PHONY : exp_q2/fast

#=============================================================================
# Target rules for targets named exp_q2_a

# Build rule for target.
exp_q2_a: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 exp_q2_a
.PHONY : exp_q2_a

# fast build rule for target.
exp_q2_a/fast:
	$(MAKE) $(MAKESILENT) -f exp/CMakeFiles/exp_q2_a.dir/build.make exp/CMakeFiles/exp_q2_a.dir/build
.PHONY : exp_q2_a/fast

#=============================================================================
# Target rules for targets named exp_q2_b

# Build rule for target.
exp_q2_b: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 exp_q2_b
.PHONY : exp_q2_b

# fast build rule for target.
exp_q2_b/fast:
	$(MAKE) $(MAKESILENT) -f exp/CMakeFiles/exp_q2_b.dir/build.make exp/CMakeFiles/exp_q2_b.dir/build
.PHONY : exp_q2_b/fast

#=============================================================================
# Target rules for targets named exp_q2_eps

# Build rule for target.
exp_q2_eps: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 exp_q2_eps
.PHONY : exp_q2_eps

# fast build rule for target.
exp_q2_eps/fast:
	$(MAKE) $(MAKESILENT) -f exp/CMakeFiles/exp_q2_eps.dir/build.make exp/CMakeFiles/exp_q2_eps.dir/build
.PHONY : exp_q2_eps/fast

#=============================================================================
# Target rules for targets named exp_q3

# Build rule for target.
exp_q3: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 exp_q3
.PHONY : exp_q3

# fast build rule for target.
exp_q3/fast:
	$(MAKE) $(MAKESILENT) -f exp/CMakeFiles/exp_q3.dir/build.make exp/CMakeFiles/exp_q3.dir/build
.PHONY : exp_q3/fast

#=============================================================================
# Target rules for targets named exp_q3_a

# Build rule for target.
exp_q3_a: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 exp_q3_a
.PHONY : exp_q3_a

# fast build rule for target.
exp_q3_a/fast:
	$(MAKE) $(MAKESILENT) -f exp/CMakeFiles/exp_q3_a.dir/build.make exp/CMakeFiles/exp_q3_a.dir/build
.PHONY : exp_q3_a/fast

#=============================================================================
# Target rules for targets named exp_q3_b

# Build rule for target.
exp_q3_b: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 exp_q3_b
.PHONY : exp_q3_b

# fast build rule for target.
exp_q3_b/fast:
	$(MAKE) $(MAKESILENT) -f exp/CMakeFiles/exp_q3_b.dir/build.make exp/CMakeFiles/exp_q3_b.dir/build
.PHONY : exp_q3_b/fast

#=============================================================================
# Target rules for targets named exp_q4

# Build rule for target.
exp_q4: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 exp_q4
.PHONY : exp_q4

# fast build rule for target.
exp_q4/fast:
	$(MAKE) $(MAKESILENT) -f exp/CMakeFiles/exp_q4.dir/build.make exp/CMakeFiles/exp_q4.dir/build
.PHONY : exp_q4/fast

#=============================================================================
# Target rules for targets named exp_q4_a

# Build rule for target.
exp_q4_a: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 exp_q4_a
.PHONY : exp_q4_a

# fast build rule for target.
exp_q4_a/fast:
	$(MAKE) $(MAKESILENT) -f exp/CMakeFiles/exp_q4_a.dir/build.make exp/CMakeFiles/exp_q4_a.dir/build
.PHONY : exp_q4_a/fast

#=============================================================================
# Target rules for targets named exp_q4_b

# Build rule for target.
exp_q4_b: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 exp_q4_b
.PHONY : exp_q4_b

# fast build rule for target.
exp_q4_b/fast:
	$(MAKE) $(MAKESILENT) -f exp/CMakeFiles/exp_q4_b.dir/build.make exp/CMakeFiles/exp_q4_b.dir/build
.PHONY : exp_q4_b/fast

#=============================================================================
# Target rules for targets named exp_q4_eps

# Build rule for target.
exp_q4_eps: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 exp_q4_eps
.PHONY : exp_q4_eps

# fast build rule for target.
exp_q4_eps/fast:
	$(MAKE) $(MAKESILENT) -f exp/CMakeFiles/exp_q4_eps.dir/build.make exp/CMakeFiles/exp_q4_eps.dir/build
.PHONY : exp_q4_eps/fast

#=============================================================================
# Target rules for targets named exp_q5

# Build rule for target.
exp_q5: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 exp_q5
.PHONY : exp_q5

# fast build rule for target.
exp_q5/fast:
	$(MAKE) $(MAKESILENT) -f exp/CMakeFiles/exp_q5.dir/build.make exp/CMakeFiles/exp_q5.dir/build
.PHONY : exp_q5/fast

#=============================================================================
# Target rules for targets named exp_q5_b

# Build rule for target.
exp_q5_b: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 exp_q5_b
.PHONY : exp_q5_b

# fast build rule for target.
exp_q5_b/fast:
	$(MAKE) $(MAKESILENT) -f exp/CMakeFiles/exp_q5_b.dir/build.make exp/CMakeFiles/exp_q5_b.dir/build
.PHONY : exp_q5_b/fast

#=============================================================================
# Target rules for targets named exp_q5_a

# Build rule for target.
exp_q5_a: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 exp_q5_a
.PHONY : exp_q5_a

# fast build rule for target.
exp_q5_a/fast:
	$(MAKE) $(MAKESILENT) -f exp/CMakeFiles/exp_q5_a.dir/build.make exp/CMakeFiles/exp_q5_a.dir/build
.PHONY : exp_q5_a/fast

#=============================================================================
# Target rules for targets named exp_q6

# Build rule for target.
exp_q6: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 exp_q6
.PHONY : exp_q6

# fast build rule for target.
exp_q6/fast:
	$(MAKE) $(MAKESILENT) -f exp/CMakeFiles/exp_q6.dir/build.make exp/CMakeFiles/exp_q6.dir/build
.PHONY : exp_q6/fast

#=============================================================================
# Target rules for targets named exp_q6_b

# Build rule for target.
exp_q6_b: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 exp_q6_b
.PHONY : exp_q6_b

# fast build rule for target.
exp_q6_b/fast:
	$(MAKE) $(MAKESILENT) -f exp/CMakeFiles/exp_q6_b.dir/build.make exp/CMakeFiles/exp_q6_b.dir/build
.PHONY : exp_q6_b/fast

#=============================================================================
# Target rules for targets named exp_q7

# Build rule for target.
exp_q7: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 exp_q7
.PHONY : exp_q7

# fast build rule for target.
exp_q7/fast:
	$(MAKE) $(MAKESILENT) -f exp/CMakeFiles/exp_q7.dir/build.make exp/CMakeFiles/exp_q7.dir/build
.PHONY : exp_q7/fast

#=============================================================================
# Target rules for targets named exp_q7_b

# Build rule for target.
exp_q7_b: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 exp_q7_b
.PHONY : exp_q7_b

# fast build rule for target.
exp_q7_b/fast:
	$(MAKE) $(MAKESILENT) -f exp/CMakeFiles/exp_q7_b.dir/build.make exp/CMakeFiles/exp_q7_b.dir/build
.PHONY : exp_q7_b/fast

#=============================================================================
# Target rules for targets named exp_q8

# Build rule for target.
exp_q8: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 exp_q8
.PHONY : exp_q8

# fast build rule for target.
exp_q8/fast:
	$(MAKE) $(MAKESILENT) -f exp/CMakeFiles/exp_q8.dir/build.make exp/CMakeFiles/exp_q8.dir/build
.PHONY : exp_q8/fast

#=============================================================================
# Target rules for targets named exp_q8_b

# Build rule for target.
exp_q8_b: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 exp_q8_b
.PHONY : exp_q8_b

# fast build rule for target.
exp_q8_b/fast:
	$(MAKE) $(MAKESILENT) -f exp/CMakeFiles/exp_q8_b.dir/build.make exp/CMakeFiles/exp_q8_b.dir/build
.PHONY : exp_q8_b/fast

#=============================================================================
# Target rules for targets named exp_q8_eps

# Build rule for target.
exp_q8_eps: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 exp_q8_eps
.PHONY : exp_q8_eps

# fast build rule for target.
exp_q8_eps/fast:
	$(MAKE) $(MAKESILENT) -f exp/CMakeFiles/exp_q8_eps.dir/build.make exp/CMakeFiles/exp_q8_eps.dir/build
.PHONY : exp_q8_eps/fast

#=============================================================================
# Target rules for targets named exp_q2_scale

# Build rule for target.
exp_q2_scale: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 exp_q2_scale
.PHONY : exp_q2_scale

# fast build rule for target.
exp_q2_scale/fast:
	$(MAKE) $(MAKESILENT) -f exp/CMakeFiles/exp_q2_scale.dir/build.make exp/CMakeFiles/exp_q2_scale.dir/build
.PHONY : exp_q2_scale/fast

#=============================================================================
# Target rules for targets named exp_q4_scale

# Build rule for target.
exp_q4_scale: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 exp_q4_scale
.PHONY : exp_q4_scale

# fast build rule for target.
exp_q4_scale/fast:
	$(MAKE) $(MAKESILENT) -f exp/CMakeFiles/exp_q4_scale.dir/build.make exp/CMakeFiles/exp_q4_scale.dir/build
.PHONY : exp_q4_scale/fast

#=============================================================================
# Target rules for targets named exp_q8_scale

# Build rule for target.
exp_q8_scale: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 exp_q8_scale
.PHONY : exp_q8_scale

# fast build rule for target.
exp_q8_scale/fast:
	$(MAKE) $(MAKESILENT) -f exp/CMakeFiles/exp_q8_scale.dir/build.make exp/CMakeFiles/exp_q8_scale.dir/build
.PHONY : exp_q8_scale/fast

#=============================================================================
# Target rules for targets named exp_selection

# Build rule for target.
exp_selection: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 exp_selection
.PHONY : exp_selection

# fast build rule for target.
exp_selection/fast:
	$(MAKE) $(MAKESILENT) -f exp/CMakeFiles/exp_selection.dir/build.make exp/CMakeFiles/exp_selection.dir/build
.PHONY : exp_selection/fast

#=============================================================================
# Target rules for targets named exp_parallel_join

# Build rule for target.
exp_parallel_join: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 exp_parallel_join
.PHONY : exp_parallel_join

# fast build rule for target.
exp_parallel_join/fast:
	$(MAKE) $(MAKESILENT) -f exp/CMakeFiles/exp_parallel_join.dir/build.make exp/CMakeFiles/exp_parallel_join.dir/build
.PHONY : exp_parallel_join/fast

#=============================================================================
# Target rules for targets named exp_plan_test

# Build rule for target.
exp_plan_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 exp_plan_test
.PHONY : exp_plan_test

# fast build rule for target.
exp_plan_test/fast:
	$(MAKE) $(MAKESILENT) -f exp/CMakeFiles/exp_plan_test.dir/build.make exp/CMakeFiles/exp_plan_test.dir/build
.PHONY : exp_plan_test/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... exp_parallel_join"
	@echo "... exp_plan_test"
	@echo "... exp_q1"
	@echo "... exp_q1_a"
	@echo "... exp_q1_b"
	@echo "... exp_q2"
	@echo "... exp_q2_a"
	@echo "... exp_q2_b"
	@echo "... exp_q2_eps"
	@echo "... exp_q2_scale"
	@echo "... exp_q3"
	@echo "... exp_q3_a"
	@echo "... exp_q3_b"
	@echo "... exp_q4"
	@echo "... exp_q4_a"
	@echo "... exp_q4_b"
	@echo "... exp_q4_eps"
	@echo "... exp_q4_scale"
	@echo "... exp_q5"
	@echo "... exp_q5_a"
	@echo "... exp_q5_b"
	@echo "... exp_q6"
	@echo "... exp_q6_b"
	@echo "... exp_q7"
	@echo "... exp_q7_b"
	@echo "... exp_q8"
	@echo "... exp_q8_b"
	@echo "... exp_q8_eps"
	@echo "... exp_q8_scale"
	@echo "... exp_selection"
	@echo "... test_joetest"
	@echo "... test_joetest2"
	@echo "... test_template1"
	@echo "... test_template1Test"
	@echo "... test_template2"
	@echo "... test_template2Test"
	@echo "... test_template3"
	@echo "... test_template3Test"
	@echo "... test_template4"
	@echo "... test_template4Test"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

